-- Returns country code -> {name, regdomain}
-- Regdomain is 0 for the default, limited domain and 1 for the
-- regdomain supporting wifi channel 12 and 13.
return {
	{"AF", "AFGHANISTAN", 0},
	{"AL", "ALBANIA", 1},
	{"DZ", "ALGERIA", 1},
	{"AS", "AMERICAN SAMOA", 0},
	{"AD", "ANDORRA", 0},
	{"AO", "ANGOLA", 0},
	{"AI", "ANGUILLA", 0},
	{"AQ", "ANTARCTICA", 0},
	{"AG", "ANTIGUA/BARBUDA", 0},
	{"AR", "ARGENTINA", 1},
	{"AM", "ARMENIA", 1},
	{"AW", "ARUBA", 0},
	{"AU", "AUSTRALIA", 1},
	{"AT", "AUSTRIA", 1},
	{"AZ", "AZERBAIJAN", 1},
	{"BS", "BAHAMAS", 0},
	{"BH", "BAHRAIN", 1},
	{"BD", "BANGLADESH", 0},
	{"BB", "BARBADOS", 0},
	{"BY", "BELARUS", 1},
	{"BE", "BELGIUM", 1},
	{"BZ", "BELIZE", 1},
	{"BJ", "BENIN", 0},
	{"BM", "BERMUDA", 0},
	{"BT", "BHUTAN", 0},
	{"BO", "BOLIVIA", 1},
	{"BA", "BOSNIA/HERZEGOVINA", 0},
	{"BW", "BOTSWANA", 0},
	{"BV", "BOUVET ISLAND", 0},
	{"BR", "BRAZIL", 1},
	{"BG", "BULGARIA", 1},
	{"BF", "BURKINA FASO", 0},
	{"BI", "BURUNDI", 0},
	{"KH", "CAMBODIA", 0},
	{"CM", "CAMEROON", 0},
	{"CA", "CANADA", 0},
	{"CV", "CAPE VERDE", 0},
	{"KY", "CAYMAN ISLANDS", 0},
	{"TD", "CHAD", 0},
	{"CL", "CHILE", 1},
	{"CN", "CHINA", 1},
	{"CX", "CHRISTMAS ISLAND", 0},
	{"CO", "COLOMBIA", 0},
	{"KM", "COMOROS", 0},
	{"CG", "CONGO", 0},
	{"CD", "CONGO", 0},
	{"CK", "COOK ISLANDS", 0},
	{"CR", "COSTA RICA", 1},
	{"HR", "CROATIA", 0},
	{"CU", "CUBA", 0},
	{"CY", "CYPRUS", 1},
	{"CZ", "CZECH REPUBLIC", 1},
	{"DK", "DENMARK", 1},
	{"DJ", "DJIBOUTI", 0},
	{"DM", "DOMINICA", 0},
	{"DO", "DOMINICAN REPUBLIC", 0},
	{"EC", "ECUADOR", 1},
	{"EG", "EGYPT", 1},
	{"SV", "EL SALVADOR", 1},
	{"GQ", "EQUATORIAL GUINEA", 0},
	{"ER", "ERITREA", 0},
	{"EE", "ESTONIA", 1},
	{"ET", "ETHIOPIA", 0},
	{"FO", "FAROE ISLANDS", 0},
	{"FJ", "FIJI", 0},
	{"FI", "FINLAND", 1},
	{"FR", "FRANCE", 1},
	{"GA", "GABON", 0},
	{"GM", "GAMBIA", 0},
	{"GE", "GEORGIA", 1},
	{"DE", "GERMANY", 1},
	{"GH", "GHANA", 0},
	{"GI", "GIBRALTAR", 0},
	{"GR", "GREECE", 1},
	{"GL", "GREENLAND", 0},
	{"GD", "GRENADA", 0},
	{"GP", "GUADELOUPE", 0},
	{"GU", "GUAM", 0},
	{"GT", "GUATEMALA", 0},
	{"GG", "GUERNSEY", 0},
	{"GW", "GUINEA-BISSAU", 0},
	{"GN", "GUINEA", 0},
	{"GY", "GUYANA", 0},
	{"HT", "HAITI", 0},
	{"VA", "VATICAN", 0},
	{"HN", "HONDURAS", 1},
	{"HK", "HONG KONG", 0},
	{"HU", "HUNGARY", 1},
	{"IS", "ICELAND", 1},
	{"IN", "INDIA", 1},
	{"ID", "INDONESIA", 1},
	{"IR", "IRAN", 1},
	{"IQ", "IRAQ", 0},
	{"IE", "IRELAND", 1},
	{"IM", "ISLE OF MAN", 0},
	{"IL", "ISRAEL", 1},
	{"IT", "ITALY", 1},
	{"JM", "JAMAICA", 0},
	{"JP", "JAPAN", 1},
	{"JE", "JERSEY", 0},
	{"JO", "JORDAN", 1},
	{"KZ", "KAZAKHSTAN", 1},
	{"KE", "KENYA", 0},
	{"KI", "KIRIBATI", 0},
	{"KW", "KUWAIT", 1},
	{"KG", "KYRGYZSTAN", 0},
	{"AX", "LAND ISLANDS", 0},
	{"LV", "LATVIA", 1},
	{"LB", "LEBANON", 1},
	{"BL", "LEMY", 0},
	{"LS", "LESOTHO", 0},
	{"LR", "LIBERIA", 0},
	{"LY", "LIBYA", 0},
	{"LI", "LIECHTENSTEIN", 1},
	{"LT", "LITHUANIA", 1},
	{"LU", "LUXEMBOURG", 1},
	{"MO", "MACAO", 1},
	{"MK", "MACEDONIA", 1},
	{"MG", "MADAGASCAR", 0},
	{"MW", "MALAWI", 0},
	{"MY", "MALAYSIA", 1},
	{"MV", "MALDIVES", 0},
	{"ML", "MALI", 0},
	{"MT", "MALTA", 0},
	{"MH", "MARSHALL ISLANDS", 0},
	{"MQ", "MARTINIQUE", 0},
	{"MR", "MAURITANIA", 0},
	{"MU", "MAURITIUS", 0},
	{"YT", "MAYOTTE", 0},
	{"MX", "MEXICO", 0},
	{"FM", "MICRONESIA", 0},
	{"MD", "MOLDOVA", 0},
	{"MC", "MONACO", 1},
	{"MN", "MONGOLIA", 0},
	{"ME", "MONTENEGRO", 0},
	{"MS", "MONTSERRAT", 0},
	{"MA", "MOROCCO", 0},
	{"MZ", "MOZAMBIQUE", 0},
	{"MM", "MYANMAR", 0},
	{"NA", "NAMIBIA", 1},
	{"NR", "NAURU", 0},
	{"NP", "NEPAL", 0},
	{"NL", "NETHERLANDS", 1},
	{"NC", "NEW CALEDONIA", 0},
	{"NZ", "NEW ZEALAND", 1},
	{"NI", "NICARAGUA", 0},
	{"NG", "NIGERIA", 0},
	{"NE", "NIGER", 0},
	{"NU", "NIUE", 0},
	{"NF", "NORFOLK ISLAND", 0},
	{"NO", "NORWAY", 0},
	{"OM", "OMAN", 1},
	{"PK", "PAKISTAN", 1},
	{"PW", "PALAU", 0},
	{"PS", "PALESTINIA", 0},
	{"PA", "PANAMA", 0},
	{"PG", "PAPUA NEW GUINEA", 0},
	{"PY", "PARAGUAY", 0},
	{"PE", "PERU", 1},
	{"PH", "PHILIPPINES", 1},
	{"PN", "PITCAIRN", 0},
	{"PL", "POLAND", 1},
	{"PT", "PORTUGAL", 1},
	{"PR", "PUERTO RICO", 0},
	{"QA", "QATAR", 1},
	{"RE", "REUNION", 0},
	{"RO", "ROMANIA", 1},
	{"RU", "RUSSIA", 1},
	{"RW", "RWANDA", 0},
	{"WS", "SAMOA", 0},
	{"SM", "SAN MARINO", 0},
	{"SA", "SAUDI ARABIA", 1},
	{"SN", "SENEGAL", 0},
	{"RS", "SERBIA", 0},
	{"SC", "SEYCHELLES", 0},
	{"SL", "SIERRA LEONE", 0},
	{"SG", "SINGAPORE", 1},
	{"SK", "SLOVAKIA", 1},
	{"SI", "SLOVENIA", 1},
	{"SB", "SOLOMON ISLANDS", 0},
	{"SO", "SOMALIA", 0},
	{"ZA", "SOUTH AFRICA", 1},
	{"ES", "SPAIN", 1},
	{"LK", "SRI LANKA", 0},
	{"SD", "SUDAN", 0},
	{"SR", "SURINAME", 0},
	{"SZ", "SWAZILAND", 0},
	{"SE", "SWEDEN", 1},
	{"CH", "SWITZERLAND", 1},
	{"TW", "TAIWAN", 0},
	{"TJ", "TAJIKISTAN", 0},
	{"TZ", "TANZANIA", 0},
	{"CI", "TE D'IVOIRE", 0},
	{"TH", "THAILAND", 1},
	{"TL", "TIMOR-LESTE", 0},
	{"TG", "TOGO", 0},
	{"TK", "TOKELAU", 0},
	{"TO", "TONGA", 0},
	{"TN", "TUNISIA", 1},
	{"TR", "TURKEY", 1},
	{"TM", "TURKMENISTAN", 0},
	{"TV", "TUVALU", 0},
	{"UG", "UGANDA", 0},
	{"UA", "UKRAINE", 1},
	{"AE", "UNITED ARAB EMIRATES", 1},
	{"GB", "UNITED KINGDOM", 1},
	{"US", "UNITED STATES", 0},
	{"UY", "URUGUAY", 1},
	{"UZ", "UZBEKISTAN", 0},
	{"VU", "VANUATU", 0},
	{"VE", "VENEZUELA", 1},
	{"VN", "VIET NAM", 1},
	{"YE", "YEMEN", 1},
	{"ZM", "ZAMBIA", 0},
	{"ZW", "ZIMBABWE", 1}
}
