
# (C) 2013 CarrierWrt.org

#
# Debug mode build
#

define Build/debug
	CONFIG += \
		CONFIG_BUSYBOX_CONFIG_FEATURE_INIT_COREDUMPS=y \
		CONFIG_PACKAGE_system-debug=y \
		CONFIG_PACKAGE_kmod-usb-storage=y \
		CONFIG_PACKAGE_kmod-fs-ext4=y \
		CONFIG_PACKAGE_block-mount=y \
		CONFIG_PACKAGE_e2fsprogs=y \
		CONFIG_PACKAGE_dmsetup=y \
		CONFIG_PACKAGE_dm-verity=y
endef
