#!/usr/bin/lua
-- (c) 2008 john@phrozen.org GPLv2

-- mount is a registered service, so use the api to start/stop it
local srv = require("luci.fon.service")
local service = srv.Service("uploadd")
if not(service:status()) then
	service:start()
end
