#!/bin/sh /etc/rc.common

START=20

start() {
	local done
	config_load fon
	config_get done "thinclient" done
	[ -z "$done" ] || return 0
	/bin/thinclient start
	uci_set_state fon thinclient done 1
}

boot() {
	# Copy the fatserver known hosts file to root's homedir
	mkdir -p ~root/.ssh
	cp /etc/dropbear/known_hosts ~root/.ssh
}
