#!/usr/bin/lua
-- (c) 2008 john@phrozen.org GPLv2

-- watchdog is a registered service, so use the api to start/stop it
local srv = require("luci.fon.service")
local service = srv.Service("watchdog")
service:start("-t", "5", "-F", "/dev/watchdog")
