
# (C) 2013 CarrierWrt.org

#
# Target: ar2315
#

define Target/draginoV1

	CONFIG += \
		CONFIG_TARGET_atheros=y \
		CONFIG_TARGET_atheros_Default=y \
		CONFIG_TARGET_BOARD="atheros" \
		CONFIG_TARGET_ARCH_PACKAGES="atheros" \
		CONFIG_TARGET_ROOTFS_JFFS2=y \
		CONFIG_LINUX_2_6_30=y \
		CONFIG_LINUX_2_6=y \
		CONFIG_PACKAGE_draginoV1=y

	IMAGES := \
		ar71xx/openwrt-ar71xx-generic-tl-wr703n-v1-squashfs-factory.bin \
		ar71xx/openwrt-ar71xx-generic-tl-wr703n-v1-squashfs-sysupgrade.bin

endef
