
# (C) 2013 CarrierWrt.org

#
# Target: ar2315
#

define Target/draginoV1

	CONFIG += \
		CONFIG_TARGET_atheros=y \
		CONFIG_TARGET_atheros_Default=y \
		CONFIG_TARGET_BOARD="atheros" \
		CONFIG_TARGET_ARCH_PACKAGES="atheros" \
		CONFIG_TARGET_ROOTFS_JFFS2=y \
		CONFIG_LINUX_2_6_30=y \
		CONFIG_LINUX_2_6=y \
		CONFIG_PACKAGE_draginoV1=y

	IMAGES := \
		atheros/openwrt-atheros-combined.squashfs.img \
		atheros/openwrt-atheros-root.squashfs \
		atheros/openwrt-atheros-vmlinux.lzma

endef
